### ISSUE TITLE
Idea: OpenCL-backed storage

### ISSUE THREAD

**Issue by michaelmelanson** [amethyst/specs#553]
I have [a scientific simulation / numerical computation project](https://github.com/michaelmelanson/spiking-neural-net) I've written using Specs. But last night I did a spike where I prototyped an version that offloaded the calculations to the GPU via OpenCL, and I saw a 100x performance improvement over the Specs (i.e, CPU-based) version. That's kind of hard to ignore.

It occurred to me that if Specs had a component storage type backed by OpenCL buffers, then you could write Systems that apply OpenCL kernels to the data, and thereby make a Specs application that offloads some calculations to the GPU. You'd get to keep Specs' entity management, as well as have other systems that do CPU-based work in the same application, while shifting the heaviest lifting to the GPU.

Has any thinking been done on this front, or any related work? What major challenges do you see in pulling this off?

**Comment by torkleyy** [comment]
This sound really interesting! Unfortunately, I don't have any experience with OpenCL.

I'm wondering how much we'd have to tie such an implementation to a specific OpenCL backend.

**Comment by torkleyy** [comment]
_further activity_

**Comment by OvermindDL1** [comment]
Still very relevant!

**Comment by michaelmelanson** [comment]
This is awesome work, thanks!

**Comment by willglynn** [comment]
#634 landed in `master`, bringing [slice access to selected storages](https://github.com/slide-rs/specs/blob/master/docs/tutorials/src/05_storages.md#slices). This is sufficient for my OpenCL needs. Usage:

```rust
impl<'a> System<'a> for SomeSystem {
    type SystemData = (WriteStorage<'a, Something>, );

    fn run(&mut self, (mut some_storage, ): Self::SystemData) {
        // 1. get a mutable slice of the component storage
        let slice = some_storage.unprotected_storage_mut().as_mut_slice();

        // 2. process the slice with OpenCL or whatever

        // 3. there is no step 3
    }
}
```

Does anyone here need `specs` to do something more before closing this issue?

**Comment by jkelleyrtp** [comment]
Awesome work! Does anyone have some example code I can work off of? I'd like to add webgl/wgpu backend so specs can actually be multithreaded in the browser.

**Comment by willglynn** [comment]
@jkelleyrtp I'm not terribly a WebGL expert, but it seems like [`texImage2D()`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D) would be your path in and [`readPixels()`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels) would be your path out. Both take `ArrayBufferView`s, which are 1:1 with slices.

Over in `web-sys`, these are [`tex_image_2d_with_…_and_u8_array_and_src_offset()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGl2RenderingContext.html#method.tex_image_2d_with_i32_and_i32_and_i32_and_format_and_type_and_u8_array_and_src_offset) and [`read_pixels_with_u8_array_and_dst_offset()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGl2RenderingContext.html#method.read_pixels_with_u8_array_and_dst_offset), functions which take a `&[u8]` and a `&mut [u8]` respectively. To plug this into `specs`, you'd make a `System` which asks a `Storage` for `as_mut_slice()`, asks WebGL to copy that slice into a texture, runs a computation using an appropriate shader, asks WebGL to copy the result back into the storage's slice, and returns on completion.

There's lots of details here about exactly how to shape the component `struct`, what pixel format the textures need to be, how to glue all this into your existing rendering pipeline, etc. Particularly in the WebGL case I expect it's a lot more complicated than using `ocl`. This is why I think this issue can be closed – `specs` now provides the escape hatches needed to do stuff like this, and it doesn't make sense for `specs` to go any further to provide better support of any specific application.
