### ISSUE TITLE
FlaggedStorage doc update require 

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/specs#612]
The example on this page is outdated: https://slide-rs.github.io/specs-website/docs/docs/0.10/specs/struct.FlaggedStorage.html

```
 for (entity, _) in (&*entities, &comps.check()).join() {
             if true { // check whether this component should be modified.
                 match comps.get_mut(entity) {
                     Some(component) => { /* ... */ },
                     None => { /* ... */ },
                 }
             }
         }
```

The function check got replaced with the function mask which now return a reference.

Check the issue here: https://github.com/slide-rs/specs/issues/304

**Comment by Imberflur** [comment]
It looks like the example was changed to use `restrict_mut` https://docs.rs/specs/0.18.0/specs/struct.FlaggedStorage.html
