### ISSUE TITLE
The website is out of date with release 0.15.0

### ISSUE THREAD

**Issue by xgalaxy** [amethyst/specs#628]
## Description

The website:
https://slide-rs.github.io/specs/

Does not contain the documentation that is for 0.15.0 release.

**Comment by torkleyy** [comment]
Yes, that's definitely confusing. The new site is https://specs.netlify.com

Not sure what to do about the old link, we should at least forward it...

**Comment by VitalyAnkh** [comment]
@torkleyy Why not update the book link in `README`? I didn't turn to this issue until I found the code in the book link(in `README`) failed to compile.

**Comment by azriel91** [comment]
Closing -- the book link is up to date :v:
