### ISSUE TITLE
Components require `Send` + `Sync` even when parallel feature is disabled

### ISSUE THREAD

**Issue by chinedufn** [amethyst/specs#673]
## Problem

`specs` does not allow you to use resources that aren't `Send` + `Sync`, even if the parallel feature is disabled.

This is an issue for me because I'm using `specs` in an application that is compiled to WebAssembly.

On the WebAssembly target one of my resources is a `wasm_bindgen::JsValue` - which is a type that at this time can't implement `Send` safely.

## Potential solution

Right now `Component` is defined as

```rust
pub trait Component: Any + Sized {
    /// Associated storage type for this component.
    type Storage: UnprotectedStorage<Self> + Any + Send + Sync;
}
```

Perhaps we can change this to

```rust
pub trait Component: Any + Sized {
    /// Associated storage type for this component.
    #[cfg(feature = "parallel")
    type Storage: UnprotectedStorage<Self> + Any + Send + Sync;
    #[cfg(not(feature = "parallel"))
    type Storage: UnprotectedStorage<Self> + Any;
}
```

I'd be happy to work on this (or any better approach)

**Comment by WaDelma** [comment]
As I have understood Cargo features should be additive: Adding a feature flag shouldn't prevent existing code from building.
If we do this change this will no longer be the case.

I do agree that this is unfortunate and should be fixed.

**Comment by chinedufn** [comment]
Wouldn't doing this change mean that the `parallel` feature is additive since it would add `Send + Sync`?

Or am I misunderstanding what you're suggesting?

Is there a patch for this that you'd accept. I'd be more than happy to implement whatever we need here!

**Comment by WaDelma** [comment]
Actually I am no longer sure if additivity requires existing code from building. It's more about not having mutually exclusive features. The reason for it is that if one crate depends on specs with a feature on and another without that feature then if third crate depends on those both there will be problems.

So maybe it's actually okay.

**Comment by WaDelma** [comment]
What I mean is that if indeed additivity of cargo features require existing code to build when a feature is enabled then I don't know how to fix the problem.

There is already cases of adding `no-std` feature which prevents code allocating from building, so probably making `parallel` to add `Send + Sync` bound is fine.

**Comment by chinedufn** [comment]
Opened a PR in `shred` here -> https://github.com/amethyst/shred/pull/186

And then in `specs` here -> https://github.com/amethyst/specs/pull/674

**Comment by azriel91** [comment]
> Wouldn't doing this change mean that the `parallel` feature is additive since it would add `Send + Sync`?

actually the *addition* of the trait bound is *subtraction* of what the storage type *accepts* :joy:

If we strictly adhere to "enabling the cargo feature means existing code still builds"-rule, then we have to swap the `"parallel"` feature for a `"serial"` or `"no-parallel"` feature instead (and have the parallel-enabled code the default).

Other perspective, it's likely more natural to think of `"parallel"` features as being more complex and hence you would "enable parallel" rather than "enable `serial`" / "enable `no-parallel`".

**Comment by chinedufn** [comment]
Ah nice - `no-parallel` makes sense to me - I can make that change across both the `specs` and `shred` PRs. 
As well as bump the minor version for both packages.

Does that sound good? Would you be down to merge that once completed or is there anything else y'all would like to see?

Thanks!

**Comment by azriel91** [comment]
I'd be happy with that, but would like to hear from @WaDelma.
The `"no-std"` aka enable-feature-to-disable-code pattern isn't yet in this repository, so I think it's good to not introduce it.

**Comment by WaDelma** [comment]
That isn't all that great solutions either: `no-parallel` would remove bunch of types such as `ParJoin`.

I didn't find that much information about on how cargo features should be used, but I think it's better to have `parallel` feature as it doesn't remove types (though it makes some types more strict)

**Comment by azriel91** [comment]
Theoretically a `no-parallel` `ParJoin` could use a serial implementation, but that's something that *could* be done in this case and not likely a general pattern :stuck_out_tongue:.

**Comment by chinedufn** [comment]
The `parallel` feature adds a crate (`rayon`) and I tend to agree that adding a feature shouldn't remove crates (even though we'd be restricting the usage with the added trait bounds.. Which is unfortunate..)

---

Given this seems to be a bit of a cargo best-practices grey area I like the idea of moving forwards with the `parallel` feature.

In that case - both PRs would be ready for your review.

https://github.com/amethyst/shred/pull/186

https://github.com/amethyst/specs/pull/674

Sound good?

Thanks!
