### ISSUE TITLE
Release 0.16.0

### ISSUE THREAD

**Issue by azriel91** [amethyst/specs#679]
There are a number of useful, yet unreleased changes since `specs 0.15.1`. This issue tracks the release so that people may pick up the changes without needing to depend on a git dependency.

Tasks:

* [x] Update `CHANGELOG.md`.
* [x] Release `specs`.
* [x] Release `specs-derive`.

**Comment by azriel91** [comment]
Released:

* :label: tag: https://github.com/amethyst/specs/tree/0.16.0
* :card_file_box: GH releases: https://github.com/amethyst/specs/releases/tag/0.16.0
* :package: crates.io: https://crates.io/crates/specs/0.16.0

**Comment by erlend-sh** [comment]
Sweet! I’ll spread the word.

One tiny thing first: For some reason it’s not tagged as the Latest release, so it appears only has a hidden tag in the Releases page.

**Comment by azriel91** [comment]
ah, looks like you have to manually create a "Release" from a tag. Have just done that :v:
