### ISSUE TITLE
How to add a component at run time that is optional? (cannot mutably borrow storage twice)

### ISSUE THREAD

**Issue by ChechyLevas** [amethyst/specs#702]
The [specs book](https://specs.amethyst.rs/docs/tutorials/08_join.html#optional-components) gives an example (copied below) of filtering when a component is optional.

```Rust
for (pos, vel, mass) in 
    (&mut pos_storage, &vel_storage, (&mut mass_storage).maybe()).join() {
    println!("Processing entity: {:?}", ent);
    *pos += *vel;

    if let Some(mass) = mass {
        let x = *vel / 300_000_000.0;
        let y = 1 - x * x;
        let y = y.sqrt();
        mass.current = mass.constant / y;
    }
}
```

But what if you wanted to add a component when it is None? I'm still learning Rust so I apologize if this turns out to be a Rust question rather than a specs question.

My failed attempts look like this

```Rust
for (entity, food, maker, offer_opt) in
            (&entities, &food_storage, &maker_storage, (&mut offer_storage).maybe()).join() {
                match offer_opt {
                    Some(offer) => 
                        println!("{:?} has an offer", &entity),
                    None => {
                        println!("{:?} has no offer, adding one", &entity);
                        offer_storage.insert(entity, Offer{lot_size: Food(4.0), price: 1.0});
                    }
                    
                }
            }
```
The above doesn't work because I am immutably borrowing `offer_storage` twice.

```Rust
for (entity, food, maker, offer) in 
            (&entities, &food_storage, &maker_storage, &mut offer_storage).join(){
                println!("{:?} has an offer", &entity);
        }

        for (entity, food, maker, ()) in
            (&entities, &food_storage, &maker_storage, !&offer_storage).join() {
                println!("{:?} has no offer, adding one", &entity);
                offer_storage.insert(entity, Offer{lot_size: Food(4.0), price: 1.0});
        }
```

The above doesn't work because I can't seem to combine the `!` operator with `mut`.

The only solution I can think of is to make a wrapper storage for `Option<Offer<T>>` but that seems a bit defeatist because it suggests that the relationship between entities and components can never be dynamic.

**Comment by WaDelma** [comment]
In general in Rust you cannot modify any data structure you are iterating over.

One way to do what you want is to use [`mask`](https://docs.rs/specs/0.16.1/specs/storage/struct.Storage.html#method.mask) to get bitset mask that tells which entities have the component. You can  then invert it to get those entities that don't have the component and then `join` with it. You have to make copy of the mask as you cannot `join` and simultaneously modify it (by changing which entities have the component).

Another way is to use [`LazyUpdate`](https://docs.rs/specs/0.16.1/specs/struct.LazyUpdate.html) to lazily add the components at the end of the game loop.

Yet another way to do this is to collect the entities you want add component to into a `Vec` which you then later process.

**Comment by ChechyLevas** [comment]
@WaDelma thanks. `LazyUpdate` works well.
