### ISSUE TITLE
Is it possible to make creating new entity in system easier?

### ISSUE THREAD

**Issue by NathanYukai** [amethyst/specs#708]
## Description
Use EntityResBuilder to build entities need to pass the storages in as parameter, which is not ideal if the entity need lots of component. 

## Motivation
What I'm trying to achieve is a nice way of creating new entity during a tick
I tried work around this by write the new entity requests into a 'Builder', fetch it and then create the entity using EntityBuilder.
But that seems impossible because that means I need to borrow World as mutable and as immutable at the same time.

Am I missing something? I'm a beginner so maybe my workaround is possible but I just didn't managed to fight the borrow checker correctly.

**Comment by WaDelma** [comment]
You can use [`LazyUpdate`](https://docs.rs/specs/0.16.1/specs/struct.LazyUpdate.html) which defers the creation of entities to end of the tick.

**Comment by NathanYukai** [comment]
Thanks ! that's what I need!
