### ISSUE TITLE
How to get an entt like view of entities within a system?

### ISSUE THREAD

**Issue by BlidDev** [amethyst/specs#743]
Hi, I have a system called `BulletSystem` that takes `Transform` and `BulletData` components. In this system I need to check if the bullet entity collides with any entity that has the `Transform` and **`EnemyData`** components. Is there anything like `view` in `entt` that just gives you a list of the entities with the required components and the ability to retrieve their components? Because I didn't see anyware a way to do that within a system.

Thanks!

**Comment by zesterer** [comment]
Simply join over the components you care about and iterate through them: https://specs.amethyst.rs/docs/tutorials/08_join.html#joining-components.

**Comment by BlidDev** [comment]
I apparently didn't understand the idea of SystemData fully yet. Thanks for your time nevertheless!
