### ISSUE TITLE
[Question] Is it possible to group components together (to all be accessed by 1 system)

### ISSUE THREAD

**Issue by DaQueenJodi** [amethyst/specs#750]
I have a lot of `*_Animation` components and I want them all to be accessed by my Animator system
is there a way I can group them together similar to how you can group entities together with `NullStorage` components?
I want to do something like this:
```rust
impl<'a> System<'a> for Animator {
    type SystemData = (
        WriteStorage<'a, Animation>, // this is the group of animations
        WriteStorage<'a, Sprite>,
        ReadStorage<'a, AnimationState>,
    );
}
```

**Comment by torkleyy** [comment]
I think you could use something like this:

```
type AnimationData<'a> = (WriteStorage<'a, AnimationComponent1>, WriteStorage<AnimationComponent2>);
```

and then use `AnimationData` in your system.

**Comment by DaQueenJodi** [comment]
thanks that's exactly what I was looking for!

**Comment by Imberflur** [comment]
closing since the question was answered
