### ISSUE TITLE
Specs vs legion

### ISSUE THREAD

**Issue by lecoqjacob** [amethyst/specs#755]
Hey sorry if this is the wrong place for this question but I was curious if I should use specs or legion to build a rougelike game?

I was going to use bracket lib and wanted to use legion, I was just curious on why it was abandoned (I assume for bevy?) and also is specs performance decent to compare with legion or bevy?

**Comment by xMAC94x** [comment]
HI @lecoqjacob  there is not much activity in this repo, so i dont know if you will get an answer. Maybe try the discord: https://discord.com/invite/amethyst

From a veloren perspective i can say we are happy with specs, but we are also the only maintainer and dependent of any recent version.

**Comment by lecoqjacob** [comment]
Thanks for the reply! I will give that a shot. As far from your perspective, do you believe specs is a good ecs lib for a game performance wise?
