### ISSUE TITLE
specs uses shred 0.13.0, which depends on mopa

### ISSUE THREAD

**Issue by AcrylicShrimp** [amethyst/specs#762]
## Description

specs currently(0.18.0) uses shred 0.13.0, which depends on mopa that is not maintained anymore. [shred already removed 
 the mopa in 0.14.0](https://github.com/amethyst/shred/issues/217), but specs still not uses it.

## Meta

Rust version: rustc 1.64.0 (a55dd71d5 2022-09-19)
Specs version / commit: 0.18.0
Operating system: macOS Ventura

## Reproduction

1. `cargo init`
2. Add `specs = { version = "0.18", features = ["derive"] }` to the generated `Cargo.toml`

## Expected behavior

It's good to upgrade `shred` to `0.14.0` to fix this issue.

**Comment by Imberflur** [comment]
Latest release now has the new `shred` version
