### ISSUE TITLE
ahash 7.5 dep yanked

### ISSUE THREAD

**Issue by juliusl** [amethyst/specs#769]
## Description

```sh
error: failed to select a version for the requirement `ahash = "^0.7.6"`
candidate versions found which didn't match: 0.8.5, 0.8.4, 0.4.1, ...
location searched: crates.io index
required by package `specs v0.20.0`
```

https://crates.io/crates/ahash/versions -- 7.5 is yanked

Related: 
https://github.com/tkaitchuck/aHash/issues/174

## Meta

Rust version:
Specs version / commit:
Operating system:

**Comment by Imberflur** [comment]
It looks like a 0.7.7 was published. Does this still fail to select a version?

**Comment by juliusl** [comment]
@Imberflur yeah the 0.7.7 backport fixed things
