### ISSUE TITLE
Compilation fails due to outdated depencendy on ahash 0.7.7

### ISSUE THREAD

**Issue by plehmkuhl** [amethyst/specs#772]
## Description

In currently nightly compilation of my project using specs fails, because of a depedency on ahash v0.7.7, which requires a now removed feature. See https://github.com/tkaitchuck/aHash/issues/195 and https://github.com/tkaitchuck/aHash/issues/200 for details.

## Meta

Rust version: rustc 1.78.0-nightly (f067fd608 2024-02-05)
Specs version: v0.20.0
Operating system: Microsoft Windows 11 Pro 10.0.22621

## Reproduction

Compile specs v.0.20.0 using rustc nightly.

## Expected behavior

Compilation succeeds without issues.

**Comment by Imberflur** [comment]
Should be fixed now since ahash released 0.7.8
