### ISSUE TITLE
The specs book domain is abandoned

### ISSUE THREAD

**Issue by xohmz** [amethyst/specs#776]
## Description

It looks like the amethyst domain, where the specs book is hosted, is abandoned: https://specs.amethyst.rs/docs/tutorials/

**Comment by benrbray** [comment]
In the meantime, the web.archive.org version seems to work:

https://web.archive.org/web/20230201225209/https://specs.amethyst.rs/docs/

**Comment by ClaasJG** [comment]
I started a conversation on [gitter](https://app.element.io/#/room/#slide-rs_specs:gitter.im/$Zcx-K8fr4wMBGAKtpWyGEgaBAQdmlSBPebTVBcSxnBI) about this.

**Comment by Imberflur** [comment]
book is now available at https://amethyst.github.io/specs/docs/tutorials/
